/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_plato_utils_FrameGrabber */

#ifndef _Included_com_plato_utils_fgrabber_FrameGrabber
#define _Included_com_plato_utils_fgrabber_FrameGrabber
#ifdef __cplusplus
extern "C"
{
#endif
  /*
 * Class:     org_mantoux_Main
 * Method:    startProcedure
 * Signature: ()V
 */
  JNIEXPORT jobject JNICALL Java_com_plato_utils_fgrabber_FrameGrabber_grabFrame(JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
